# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "edl"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julik Tarkhanov"]
  s.date = "2012-01-09"
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "README.txt",
    "Rakefile",
    "edl.gemspec",
    "illustr/edl-explain.ai",
    "lib/edl.rb",
    "lib/edl/cutter.rb",
    "lib/edl/event.rb",
    "lib/edl/grabber.rb",
    "lib/edl/linebreak_magician.rb",
    "lib/edl/parser.rb",
    "lib/edl/timewarp.rb",
    "lib/edl/transition.rb",
    "test/samples/45S_SAMPLE.EDL",
    "test/samples/FCP_REVERSE.EDL",
    "test/samples/KEY_TRANSITION.EDL",
    "test/samples/PLATES.EDL",
    "test/samples/REVERSE.EDL",
    "test/samples/SIMPLE_DISSOLVE.EDL",
    "test/samples/SPEEDUP_AND_FADEOUT.EDL",
    "test/samples/SPEEDUP_REVERSE_AND_FADEOUT.EDL",
    "test/samples/SPLICEME.EDL",
    "test/samples/TIMEWARP.EDL",
    "test/samples/TIMEWARP_HALF.EDL",
    "test/samples/TRAILER_EDL.edl",
    "test/test_edl.rb"
  ]
  s.homepage = "http://guerilla-di.org/edl"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Parser for EDL (Edit Decision List) files"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<timecode>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<flexmock>, ["~> 0.8"])
      s.add_development_dependency(%q<test-spec>, [">= 0"])
    else
      s.add_dependency(%q<timecode>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<flexmock>, ["~> 0.8"])
      s.add_dependency(%q<test-spec>, [">= 0"])
    end
  else
    s.add_dependency(%q<timecode>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<flexmock>, ["~> 0.8"])
    s.add_dependency(%q<test-spec>, [">= 0"])
  end
end

